'2222':
  ch_num: 14
  compress: 'on'
  data:
  - ant_num: '0'
    ch_cc: '0'
    ch_num: '1'
    msps: '7.68'
    offset: '0'
    width: '8'
  - ant_num: '0'
    ch_cc: '0'
    ch_num: '1'
    msps: '7.68'
    offset: '0'
    width: '8'
  - ant_num: '0'
    ch_cc: '0'
    ch_num: '1'
    msps: '7.68'
    offset: '0'
    width: '8'
  - ant_num: '0'
    ch_cc: '0'
    ch_num: '1'
    msps: '7.68'
    offset: '0'
    width: '8'
  - ant_num: '0'
    ch_cc: '0'
    ch_num: '1'
    msps: '7.68'
    offset: '0'
    width: '8'
  - ant_num: '0'
    ch_cc: '0'
    ch_num: '1'
    msps: '7.68'
    offset: '0'
    width: '8'
  - ant_num: '0'
    ch_cc: '0'
    ch_num: '1'
    msps: '7.68'
    offset: '0'
    width: '8'
  - ant_num: '0'
    ch_cc: '0'
    ch_num: '1'
    msps: '7.68'
    offset: '0'
    width: '8'
  - ant_num: '0'
    ch_cc: '0'
    ch_num: '1'
    msps: '7.68'
    offset: '0'
    width: '8'
  - ant_num: '0'
    ch_cc: '0'
    ch_num: '1'
    msps: '7.68'
    offset: '0'
    width: '8'
  - ant_num: '0'
    ch_cc: '0'
    ch_num: '1'
    msps: '7.68'
    offset: '0'
    width: '8'
  - ant_num: '0'
    ch_cc: '0'
    ch_num: '1'
    msps: '7.68'
    offset: '0'
    width: '8'
  - ant_num: '0'
    ch_cc: '0'
    ch_num: '1'
    msps: '7.68'
    offset: '0'
    width: '8'
  - ant_num: '0'
    ch_cc: '0'
    ch_num: '1'
    msps: '7.68'
    offset: '0'
    width: '8'
  interleave: 'off'
'6':
  ch_num: 6
  compress: 'on'
  data:
  - ant_num: '0'
    ch_cc: '88'
    ch_num: '1'
    msps: '7.68'
    offset: '0'
    width: '8'
  - ant_num: '0'
    ch_cc: '8'
    ch_num: '1'
    msps: '7.68'
    offset: '0'
    width: '8'
  - ant_num: '0'
    ch_cc: '2'
    ch_num: '1'
    msps: '7.68'
    offset: '0'
    width: '8'
  - ant_num: '0'
    ch_cc: '12'
    ch_num: '1'
    msps: '7.68'
    offset: '0'
    width: '8'
  - ant_num: '0'
    ch_cc: '1'
    ch_num: '1'
    msps: '7.68'
    offset: '0'
    width: '8'
  - ant_num: '0'
    ch_cc: '0'
    ch_num: '1'
    msps: '7.68'
    offset: '0'
    width: '8'
  interleave: 'on'
我问问:
  ch_num: 1
  compress: 'on'
  data:
  - ant_num: '1'
    ch_cc: '1'
    ch_num: '1'
    msps: '7.68'
    offset: '1'
    width: '8'
  interleave: 'off'
测试:
  ch_num: 4
  compress: 'on'
  data:
  - ant_num: '1'
    ch_cc: '1'
    ch_num: '20'
    msps: '7.68'
    offset: '1'
    width: '8'
  - ant_num: '1'
    ch_cc: '1'
    ch_num: '14'
    msps: '7.68'
    offset: '1'
    width: '8'
  - ant_num: '1'
    ch_cc: '1'
    ch_num: '11'
    msps: '7.68'
    offset: '1'
    width: '8'
  - ant_num: '1'
    ch_cc: '1'
    ch_num: '2'
    msps: '7.68'
    offset: '1'
    width: '8'
  interleave: 'off'
