'6':
  ch_num: 6
  compress: 'on'
  data:
  - ant_num: '0'
    ch_cc: '88'
    ch_num: '1'
    msps: '7.68'
    offset: '0'
    width: '8'
  - ant_num: '0'
    ch_cc: '8'
    ch_num: '1'
    msps: '7.68'
    offset: '0'
    width: '8'
  - ant_num: '0'
    ch_cc: '2'
    ch_num: '1'
    msps: '7.68'
    offset: '0'
    width: '8'
  - ant_num: '0'
    ch_cc: '12'
    ch_num: '1'
    msps: '7.68'
    offset: '0'
    width: '8'
  - ant_num: '0'
    ch_cc: '1'
    ch_num: '1'
    msps: '7.68'
    offset: '0'
    width: '8'
  - ant_num: '0'
    ch_cc: '0'
    ch_num: '1'
    msps: '7.68'
    offset: '0'
    width: '8'
  interleave: 'on'
