'2':
  ch_num: 2
  compress: 'on'
  data:
  - ant_num: '0'
    ch_cc: '0'
    ch_num: '1'
    msps: '7.68'
    offset: '0'
    width: '8'
  - ant_num: '0'
    ch_cc: '0'
    ch_num: '1'
    msps: '7.68'
    offset: '0'
    width: '8'
  interleave: 'off'
