cest:
  ch_num: 6
  compress: 'off'
  data:
  - ant_num: '0'
    ch_cc: '0'
    ch_num: '1'
    msps: '122.88'
    offset: '0'
    width: '16'
  - ant_num: '0'
    ch_cc: '1'
    ch_num: '1'
    msps: '122.88'
    offset: '0'
    width: '16'
  - ant_num: '0'
    ch_cc: '2'
    ch_num: '1'
    msps: '122.88'
    offset: '0'
    width: '16'
  - ant_num: '0'
    ch_cc: '3'
    ch_num: '1'
    msps: '122.88'
    offset: '0'
    width: '16'
  - ant_num: '0'
    ch_cc: '4'
    ch_num: '1'
    msps: '122.88'
    offset: '0'
    width: '16'
  - ant_num: '0'
    ch_cc: '5'
    ch_num: '1'
    msps: '122.88'
    offset: '0'
    width: '16'
  interleave: 'on'
